### ISSUE TITLE
Log in after switching users, the mouse pointer is lost

### ISSUE THREAD

**Issue by CrossCC** [ukui/ukwm#13]
Version：20.04LTS
ISO：ubuntukylin-20.04-0521-amd64.iso
Test environment：Lenovo ThinkPad-X1-Yoga

Test steps:
1. Log in user 1, enter the system, click switch user to return to the login interface
2. Log in to user 1 again

actual results:
The mouse pointer is missing
![指针丢失](https://user-images.githubusercontent.com/33095911/82779319-78571280-9e86-11ea-8448-f62584fcda12.jpg)

Open the terminal, enter the content in the terminal, then click anywhere on the desktop, the pointer resumes

**Comment by CrossCC** [comment]
> Version：20.04LTS
> ISO：ubuntukylin-20.04-0521-amd64.iso
> Test environment：Lenovo ThinkPad-X1-Yoga
> Test steps:
> 
> Log in user 1, enter the system, click switch user to return to the login interface
> Log in to user 1 again
> 
> actual results:
> The mouse pointer is missing
> Open the terminal, enter the content in the terminal, then click anywhere on the desktop, the pointer resumes

测试步骤：
1、登陆用户1，进入系统，点击切换用户回到登陆界面
2、再登陆用户1

实际结果：
鼠标指针丢失
![指针丢失](https://user-images.githubusercontent.com/33095911/82779281-61182500-9e86-11ea-98ac-21d8a24e389d.jpg)

打开终端，在终端中输入内容，再点击桌面任意位置，指针恢复

**Comment by Liang-zy** [comment]
test passef
